name: spread
description: Easy State management
version: 0.0.1
repository: https://github.com/autanalabs/spread

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
