name: spread
description: Easiest to implement state management for Flutter. Use any primitive, enum, type or entity as state. Support state event multicasting
version: 0.0.6
repository: https://github.com/autanalabs/spread

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  spread_core: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
